/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package hja.p3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.JLabel;

/**
 *
 * @author penap
 */
public class PokerFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form PokerFrame
     */
    public PokerFrame2() {
        try{
            this.setSize(1000,1000);
            initComponents();
        }catch(Exception ex){
            System.out.println("ERROR CUIDADO: " + ex.getMessage());
        }
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() throws MalformedURLException {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        
        JLabel jLabel11 = new javax.swing.JLabel();
        JLabel jLabel12 = new javax.swing.JLabel();
        JLabel jLabel13 = new javax.swing.JLabel();
        JLabel jLabel14 = new javax.swing.JLabel();
        JLabel jLabel15 = new javax.swing.JLabel();
        JLabel jLabel16 = new javax.swing.JLabel();
        JLabel jLabel17 = new javax.swing.JLabel();
        JLabel jLabel18 = new javax.swing.JLabel();
        JLabel jLabel19 = new javax.swing.JLabel();
        JLabel jLabel20 = new javax.swing.JLabel();
        JLabel jLabel21 = new javax.swing.JLabel();
        JLabel jLabel22 = new javax.swing.JLabel();
        JLabel jLabel23 = new javax.swing.JLabel();
        JLabel jLabel24 = new javax.swing.JLabel();
        JLabel jLabel25 = new javax.swing.JLabel();
        JLabel jLabel26 = new javax.swing.JLabel();
        JLabel jLabel27 = new javax.swing.JLabel();
        JLabel jLabel3 = new javax.swing.JLabel();
        JLabel jLabel4 = new javax.swing.JLabel();
        JLabel jLabel5 = new javax.swing.JLabel();
        JLabel jLabel6 = new javax.swing.JLabel();
        JLabel jLabel7 = new javax.swing.JLabel();
        JLabel jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        String imagePath = "C:\\Users\\penap\\Documents\\NetBeansProjects\\HJA-TheEquity\\src\\main\\java\\hja\\p3\\TableroPoker5.jpg";


        
        jLabel11.setText("j5c2");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, 60));

        jLabel12.setText("j5c2");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, 60));

        jLabel13.setText("j0c1");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 60));

        jLabel14.setText("j0c1");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 60));

        jLabel15.setText("j1c1");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, 60));

        jLabel16.setText("j1c2");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, 60));

        jLabel17.setText("j2c1");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, 60));

        jLabel18.setText("j2c2");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, 60));

        jLabel19.setText("j3c1");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, 60));

        jLabel20.setText("j3c2");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, -1, 60));

        jLabel21.setText("j4c1");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, 60));

        jLabel22.setText("j4c2");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, 60));

        jLabel23.setText("b0");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, 60));

        jLabel24.setText("b1");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, 60));

        jLabel25.setText("b2");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, 60));

        jLabel26.setText("b4");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, 60));

        jLabel27.setText("b3");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, 60));

        jLabel3.setText("eq0");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel4.setText("eq1");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        jLabel5.setText("eq2");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        jLabel6.setText("eq3");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, -1, -1));

        jLabel7.setText("eq4");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        jLabel8.setText("eq5");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));
        
                jLabel1.setIcon(new javax.swing.ImageIcon(imagePath)); // NOI18N
        jLabel1.setVisible(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 1000));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}

